CREATE TABLE `SIMPLE_SITE_USERS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`USERNAME` VARCHAR(50) NOT NULL,
	`PASSWORD` VARCHAR(255) NOT NULL,
	`ROLES` VARCHAR(100) NULL DEFAULT NULL,
	`NAME` VARCHAR(255) NULL DEFAULT NULL,
	`SURNAME` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `ID` (`ID`)
)
COLLATE='latin1_swedish_ci'
;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='simple_site';
SHOW TABLE STATUS FROM `simple_site`;
SHOW FUNCTION STATUS WHERE `Db`='simple_site';
SHOW PROCEDURE STATUS WHERE `Db`='simple_site';
SHOW TRIGGERS FROM `simple_site`;